// flow-typed signature: 76161f11ceb12743dccdd869082332b1
// flow-typed version: <<STUB>>/classlist-polyfill_v^1.2.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'classlist-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'classlist-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'classlist-polyfill/src/index' {
  declare module.exports: any;
}

declare module 'classlist-polyfill/tests/remove' {
  declare module.exports: any;
}

declare module 'classlist-polyfill/tests/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'classlist-polyfill/src/index.js' {
  declare module.exports: $Exports<'classlist-polyfill/src/index'>;
}
declare module 'classlist-polyfill/tests/remove.js' {
  declare module.exports: $Exports<'classlist-polyfill/tests/remove'>;
}
declare module 'classlist-polyfill/tests/tests.js' {
  declare module.exports: $Exports<'classlist-polyfill/tests/tests'>;
}
