// flow-typed signature: 3a2ab30724126088ac7fbfeed3d4a1b7
// flow-typed version: <<STUB>>/ease-component_v^1.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ease-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ease-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ease-component/index' {
  declare module.exports: $Exports<'ease-component'>;
}
declare module 'ease-component/index.js' {
  declare module.exports: $Exports<'ease-component'>;
}
