// flow-typed signature: b8f62852b40cb0a85501d04a6f097bac
// flow-typed version: <<STUB>>/esdoc-es7-plugin_v0.0.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esdoc-es7-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esdoc-es7-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esdoc-es7-plugin/out/src/Plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esdoc-es7-plugin/out/src/Plugin.js' {
  declare module.exports: $Exports<'esdoc-es7-plugin/out/src/Plugin'>;
}
