// flow-typed signature: b6da043c5cee1e1c1d702584f18f3934
// flow-typed version: <<STUB>>/expose-loader_v^0.7.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expose-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expose-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'expose-loader/index' {
  declare module.exports: $Exports<'expose-loader'>;
}
declare module 'expose-loader/index.jsx' {
  declare module.exports: $Exports<'expose-loader'>;
}
