// flow-typed signature: db04cf20c5fc96918358ae3bb865304b
// flow-typed version: <<STUB>>/mobile-detect_v^1.3.6/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobile-detect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobile-detect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobile-detect/mobile-detect-modernizr' {
  declare module.exports: any;
}

declare module 'mobile-detect/mobile-detect' {
  declare module.exports: any;
}

declare module 'mobile-detect/mobile-detect.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobile-detect/mobile-detect-modernizr.js' {
  declare module.exports: $Exports<'mobile-detect/mobile-detect-modernizr'>;
}
declare module 'mobile-detect/mobile-detect.js' {
  declare module.exports: $Exports<'mobile-detect/mobile-detect'>;
}
declare module 'mobile-detect/mobile-detect.min.js' {
  declare module.exports: $Exports<'mobile-detect/mobile-detect.min'>;
}
