// flow-typed signature: 35011ad6ac5b3a19c116b5acb6d37086
// flow-typed version: <<STUB>>/react-credit-cards_v^0.4.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-credit-cards'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-credit-cards' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-credit-cards/lib/index' {
  declare module.exports: any;
}

declare module 'react-credit-cards/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-credit-cards/lib/index.js' {
  declare module.exports: $Exports<'react-credit-cards/lib/index'>;
}
declare module 'react-credit-cards/src/index.jsx' {
  declare module.exports: $Exports<'react-credit-cards/src/index'>;
}
