// flow-typed signature: 919315ec4901808778ba50a3bbd85227
// flow-typed version: <<STUB>>/reactotron-redux_v^1.10.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reactotron-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reactotron-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reactotron-redux/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reactotron-redux/dist/index.jsx' {
  declare module.exports: $Exports<'reactotron-redux/dist/index'>;
}
