// flow-typed signature: d0d708d17f45a44ef1da6e5a4df772b9
// flow-typed version: <<STUB>>/react-hot-loader_v^3.0.0-beta/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-hot-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-hot-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-hot-loader/babel' {
  declare module.exports: any;
}

declare module 'react-hot-loader/lib/AppContainer.dev' {
  declare module.exports: any;
}

declare module 'react-hot-loader/lib/AppContainer' {
  declare module.exports: any;
}

declare module 'react-hot-loader/lib/AppContainer.prod' {
  declare module.exports: any;
}

declare module 'react-hot-loader/lib/babel/index' {
  declare module.exports: any;
}

declare module 'react-hot-loader/lib/index' {
  declare module.exports: any;
}

declare module 'react-hot-loader/lib/patch.dev' {
  declare module.exports: any;
}

declare module 'react-hot-loader/lib/patch' {
  declare module.exports: any;
}

declare module 'react-hot-loader/lib/patch.prod' {
  declare module.exports: any;
}

declare module 'react-hot-loader/lib/webpack/index' {
  declare module.exports: any;
}

declare module 'react-hot-loader/lib/webpack/makeIdentitySourceMap' {
  declare module.exports: any;
}

declare module 'react-hot-loader/lib/webpack/tagCommonJSExports' {
  declare module.exports: any;
}

declare module 'react-hot-loader/patch' {
  declare module.exports: any;
}

declare module 'react-hot-loader/webpack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-hot-loader/babel.js' {
  declare module.exports: $Exports<'react-hot-loader/babel'>;
}
declare module 'react-hot-loader/index' {
  declare module.exports: $Exports<'react-hot-loader'>;
}
declare module 'react-hot-loader/index.jsx' {
  declare module.exports: $Exports<'react-hot-loader'>;
}
declare module 'react-hot-loader/lib/AppContainer.dev.js' {
  declare module.exports: $Exports<'react-hot-loader/lib/AppContainer.dev'>;
}
declare module 'react-hot-loader/lib/AppContainer.js' {
  declare module.exports: $Exports<'react-hot-loader/lib/AppContainer'>;
}
declare module 'react-hot-loader/lib/AppContainer.prod.js' {
  declare module.exports: $Exports<'react-hot-loader/lib/AppContainer.prod'>;
}
declare module 'react-hot-loader/lib/babel/index.jsx' {
  declare module.exports: $Exports<'react-hot-loader/lib/babel/index'>;
}
declare module 'react-hot-loader/lib/index.jsx' {
  declare module.exports: $Exports<'react-hot-loader/lib/index'>;
}
declare module 'react-hot-loader/lib/patch.dev.js' {
  declare module.exports: $Exports<'react-hot-loader/lib/patch.dev'>;
}
declare module 'react-hot-loader/lib/patch.js' {
  declare module.exports: $Exports<'react-hot-loader/lib/patch'>;
}
declare module 'react-hot-loader/lib/patch.prod.js' {
  declare module.exports: $Exports<'react-hot-loader/lib/patch.prod'>;
}
declare module 'react-hot-loader/lib/webpack/index.jsx' {
  declare module.exports: $Exports<'react-hot-loader/lib/webpack/index'>;
}
declare module 'react-hot-loader/lib/webpack/makeIdentitySourceMap.js' {
  declare module.exports: $Exports<'react-hot-loader/lib/webpack/makeIdentitySourceMap'>;
}
declare module 'react-hot-loader/lib/webpack/tagCommonJSExports.js' {
  declare module.exports: $Exports<'react-hot-loader/lib/webpack/tagCommonJSExports'>;
}
declare module 'react-hot-loader/patch.js' {
  declare module.exports: $Exports<'react-hot-loader/patch'>;
}
declare module 'react-hot-loader/webpack.js' {
  declare module.exports: $Exports<'react-hot-loader/webpack'>;
}
