// flow-typed signature: a5553ac6d44352616305d411909242db
// flow-typed version: <<STUB>>/redux-diff-logger_v0.0.9/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-diff-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-diff-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-diff-logger/lib/index' {
  declare module.exports: any;
}

declare module 'redux-diff-logger/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-diff-logger/lib/index.js' {
  declare module.exports: $Exports<'redux-diff-logger/lib/index'>;
}
declare module 'redux-diff-logger/src/index.js' {
  declare module.exports: $Exports<'redux-diff-logger/src/index'>;
}
