// flow-typed signature: 341273714e1b26fba11306ce525b4b4c
// flow-typed version: <<STUB>>/rsync_v^0.6.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rsync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rsync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rsync/examples/simple' {
  declare module.exports: any;
}

declare module 'rsync/rsync' {
  declare module.exports: any;
}

declare module 'rsync/tests/accessors.test' {
  declare module.exports: any;
}

declare module 'rsync/tests/filters.test' {
  declare module.exports: any;
}

declare module 'rsync/tests/helpers/echo_input' {
  declare module.exports: any;
}

declare module 'rsync/tests/helpers/fs_helper' {
  declare module.exports: any;
}

declare module 'rsync/tests/helpers/output' {
  declare module.exports: any;
}

declare module 'rsync/tests/input.test' {
  declare module.exports: any;
}

declare module 'rsync/tests/inputwin32.test' {
  declare module.exports: any;
}

declare module 'rsync/tests/options.test' {
  declare module.exports: any;
}

declare module 'rsync/tests/shell_expansion.test' {
  declare module.exports: any;
}

declare module 'rsync/tests/shorthands.test' {
  declare module.exports: any;
}

declare module 'rsync/tests/z_output.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rsync/examples/simple.js' {
  declare module.exports: $Exports<'rsync/examples/simple'>;
}
declare module 'rsync/rsync.js' {
  declare module.exports: $Exports<'rsync/rsync'>;
}
declare module 'rsync/tests/accessors.test.js' {
  declare module.exports: $Exports<'rsync/tests/accessors.test'>;
}
declare module 'rsync/tests/filters.test.js' {
  declare module.exports: $Exports<'rsync/tests/filters.test'>;
}
declare module 'rsync/tests/helpers/echo_input.js' {
  declare module.exports: $Exports<'rsync/tests/helpers/echo_input'>;
}
declare module 'rsync/tests/helpers/fs_helper.js' {
  declare module.exports: $Exports<'rsync/tests/helpers/fs_helper'>;
}
declare module 'rsync/tests/helpers/output.js' {
  declare module.exports: $Exports<'rsync/tests/helpers/output'>;
}
declare module 'rsync/tests/input.test.js' {
  declare module.exports: $Exports<'rsync/tests/input.test'>;
}
declare module 'rsync/tests/inputwin32.test.js' {
  declare module.exports: $Exports<'rsync/tests/inputwin32.test'>;
}
declare module 'rsync/tests/options.test.js' {
  declare module.exports: $Exports<'rsync/tests/options.test'>;
}
declare module 'rsync/tests/shell_expansion.test.js' {
  declare module.exports: $Exports<'rsync/tests/shell_expansion.test'>;
}
declare module 'rsync/tests/shorthands.test.js' {
  declare module.exports: $Exports<'rsync/tests/shorthands.test'>;
}
declare module 'rsync/tests/z_output.test.js' {
  declare module.exports: $Exports<'rsync/tests/z_output.test'>;
}
