// flow-typed signature: 70d0c71b6fdaa588b23461f3cdc4c1ba
// flow-typed version: <<STUB>>/sass-mediaqueries_v^1.6.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass-mediaqueries'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass-mediaqueries' {
  declare module.exports: any;
}
