// flow-typed signature: 82aade379db4f69a6c030ce4aeafc3e4
// flow-typed version: <<STUB>>/sass-mediaqueries_v^1.6.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass-mediaqueries'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass-mediaqueries' {
  declare module.exports: any;
}
