// flow-typed signature: b61289f274588466369c07226f6f813c
// flow-typed version: <<STUB>>/scroll-doc_v^0.1.3/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scroll-doc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scroll-doc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'scroll-doc/index' {
  declare module.exports: $Exports<'scroll-doc'>;
}
declare module 'scroll-doc/index.jsx' {
  declare module.exports: $Exports<'scroll-doc'>;
}
