// flow-typed signature: 0ec856e61bd362979fc6677ceaf45bdd
// flow-typed version: <<STUB>>/selenium-server-standalone-jar_v^3.4.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'selenium-server-standalone-jar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'selenium-server-standalone-jar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'selenium-server-standalone-jar/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'selenium-server-standalone-jar/index' {
  declare module.exports: $Exports<'selenium-server-standalone-jar'>;
}
declare module 'selenium-server-standalone-jar/index.jsx' {
  declare module.exports: $Exports<'selenium-server-standalone-jar'>;
}
declare module 'selenium-server-standalone-jar/test/index.jsx' {
  declare module.exports: $Exports<'selenium-server-standalone-jar/test/index'>;
}
