// flow-typed signature: aef5a1a6e236adddf4c0f376d53b85eb
// flow-typed version: <<STUB>>/stylelint-scss_v^1.4.4/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-scss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-scss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-scss/dist/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-else-closing-brace-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-else-closing-brace-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-else-empty-line-before/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-extend-no-missing-placeholder/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-function-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-if-closing-brace-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-if-closing-brace-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-import-no-partial-extension/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-import-no-partial-leading-underscore/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-import-partial-extension-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-import-partial-extension-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-mixin-argumentless-call-parentheses/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-mixin-no-argumentless-call-parentheses/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-mixin-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/declaration-nested-properties-no-divided-groups/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/declaration-nested-properties/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/dollar-variable-colon-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/dollar-variable-colon-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/dollar-variable-colon-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/dollar-variable-empty-line-before/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/dollar-variable-no-missing-interpolation/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/dollar-variable-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/double-slash-comment-empty-line-before/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/double-slash-comment-inline/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/double-slash-comment-whitespace-inside/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/media-feature-value-dollar-variable/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/operator-no-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/operator-no-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/operator-no-unspaced/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/partial-no-import/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/percent-placeholder-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/selector-no-redundant-nesting-selector/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/atRuleParamIndex' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/beforeBlockString' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/blockString' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/configurationError' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/declarationValueIndex' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/findCommentsInRaws' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/hasBlock' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/hasEmptyLine' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/hasInterpolatingAmpersand' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/isInlineComment' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/isSingleLineString' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/isStandardRule' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/isStandardSelector' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/isStandardSyntaxProperty' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/isWhitespace' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/namespace' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/optionsHaveException' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/optionsHaveIgnored' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/parseNestedPropRoot' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/parseSelector' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/rawNodeString' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/sassValueParser/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/whitespaceChecker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-scss/dist/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/index'>;
}
declare module 'stylelint-scss/dist/rules/at-else-closing-brace-newline-after/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-else-closing-brace-newline-after/index'>;
}
declare module 'stylelint-scss/dist/rules/at-else-closing-brace-space-after/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-else-closing-brace-space-after/index'>;
}
declare module 'stylelint-scss/dist/rules/at-else-empty-line-before/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-else-empty-line-before/index'>;
}
declare module 'stylelint-scss/dist/rules/at-extend-no-missing-placeholder/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-extend-no-missing-placeholder/index'>;
}
declare module 'stylelint-scss/dist/rules/at-function-pattern/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-function-pattern/index'>;
}
declare module 'stylelint-scss/dist/rules/at-if-closing-brace-newline-after/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-if-closing-brace-newline-after/index'>;
}
declare module 'stylelint-scss/dist/rules/at-if-closing-brace-space-after/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-if-closing-brace-space-after/index'>;
}
declare module 'stylelint-scss/dist/rules/at-import-no-partial-extension/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-import-no-partial-extension/index'>;
}
declare module 'stylelint-scss/dist/rules/at-import-no-partial-leading-underscore/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-import-no-partial-leading-underscore/index'>;
}
declare module 'stylelint-scss/dist/rules/at-import-partial-extension-blacklist/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-import-partial-extension-blacklist/index'>;
}
declare module 'stylelint-scss/dist/rules/at-import-partial-extension-whitelist/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-import-partial-extension-whitelist/index'>;
}
declare module 'stylelint-scss/dist/rules/at-mixin-argumentless-call-parentheses/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-mixin-argumentless-call-parentheses/index'>;
}
declare module 'stylelint-scss/dist/rules/at-mixin-no-argumentless-call-parentheses/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-mixin-no-argumentless-call-parentheses/index'>;
}
declare module 'stylelint-scss/dist/rules/at-mixin-pattern/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-mixin-pattern/index'>;
}
declare module 'stylelint-scss/dist/rules/declaration-nested-properties-no-divided-groups/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/declaration-nested-properties-no-divided-groups/index'>;
}
declare module 'stylelint-scss/dist/rules/declaration-nested-properties/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/declaration-nested-properties/index'>;
}
declare module 'stylelint-scss/dist/rules/dollar-variable-colon-newline-after/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/dollar-variable-colon-newline-after/index'>;
}
declare module 'stylelint-scss/dist/rules/dollar-variable-colon-space-after/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/dollar-variable-colon-space-after/index'>;
}
declare module 'stylelint-scss/dist/rules/dollar-variable-colon-space-before/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/dollar-variable-colon-space-before/index'>;
}
declare module 'stylelint-scss/dist/rules/dollar-variable-empty-line-before/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/dollar-variable-empty-line-before/index'>;
}
declare module 'stylelint-scss/dist/rules/dollar-variable-no-missing-interpolation/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/dollar-variable-no-missing-interpolation/index'>;
}
declare module 'stylelint-scss/dist/rules/dollar-variable-pattern/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/dollar-variable-pattern/index'>;
}
declare module 'stylelint-scss/dist/rules/double-slash-comment-empty-line-before/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/double-slash-comment-empty-line-before/index'>;
}
declare module 'stylelint-scss/dist/rules/double-slash-comment-inline/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/double-slash-comment-inline/index'>;
}
declare module 'stylelint-scss/dist/rules/double-slash-comment-whitespace-inside/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/double-slash-comment-whitespace-inside/index'>;
}
declare module 'stylelint-scss/dist/rules/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/index'>;
}
declare module 'stylelint-scss/dist/rules/media-feature-value-dollar-variable/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/media-feature-value-dollar-variable/index'>;
}
declare module 'stylelint-scss/dist/rules/operator-no-newline-after/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/operator-no-newline-after/index'>;
}
declare module 'stylelint-scss/dist/rules/operator-no-newline-before/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/operator-no-newline-before/index'>;
}
declare module 'stylelint-scss/dist/rules/operator-no-unspaced/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/operator-no-unspaced/index'>;
}
declare module 'stylelint-scss/dist/rules/partial-no-import/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/partial-no-import/index'>;
}
declare module 'stylelint-scss/dist/rules/percent-placeholder-pattern/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/percent-placeholder-pattern/index'>;
}
declare module 'stylelint-scss/dist/rules/selector-no-redundant-nesting-selector/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/selector-no-redundant-nesting-selector/index'>;
}
declare module 'stylelint-scss/dist/utils/atRuleParamIndex.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/atRuleParamIndex'>;
}
declare module 'stylelint-scss/dist/utils/beforeBlockString.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/beforeBlockString'>;
}
declare module 'stylelint-scss/dist/utils/blockString.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/blockString'>;
}
declare module 'stylelint-scss/dist/utils/configurationError.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/configurationError'>;
}
declare module 'stylelint-scss/dist/utils/declarationValueIndex.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/declarationValueIndex'>;
}
declare module 'stylelint-scss/dist/utils/findCommentsInRaws.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/findCommentsInRaws'>;
}
declare module 'stylelint-scss/dist/utils/hasBlock.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/hasBlock'>;
}
declare module 'stylelint-scss/dist/utils/hasEmptyLine.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/hasEmptyLine'>;
}
declare module 'stylelint-scss/dist/utils/hasInterpolatingAmpersand.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/hasInterpolatingAmpersand'>;
}
declare module 'stylelint-scss/dist/utils/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/index'>;
}
declare module 'stylelint-scss/dist/utils/isInlineComment.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/isInlineComment'>;
}
declare module 'stylelint-scss/dist/utils/isSingleLineString.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/isSingleLineString'>;
}
declare module 'stylelint-scss/dist/utils/isStandardRule.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/isStandardRule'>;
}
declare module 'stylelint-scss/dist/utils/isStandardSelector.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/isStandardSelector'>;
}
declare module 'stylelint-scss/dist/utils/isStandardSyntaxProperty.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/isStandardSyntaxProperty'>;
}
declare module 'stylelint-scss/dist/utils/isWhitespace.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/isWhitespace'>;
}
declare module 'stylelint-scss/dist/utils/namespace.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/namespace'>;
}
declare module 'stylelint-scss/dist/utils/optionsHaveException.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/optionsHaveException'>;
}
declare module 'stylelint-scss/dist/utils/optionsHaveIgnored.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/optionsHaveIgnored'>;
}
declare module 'stylelint-scss/dist/utils/parseNestedPropRoot.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/parseNestedPropRoot'>;
}
declare module 'stylelint-scss/dist/utils/parseSelector.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/parseSelector'>;
}
declare module 'stylelint-scss/dist/utils/rawNodeString.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/rawNodeString'>;
}
declare module 'stylelint-scss/dist/utils/sassValueParser/index.jsx' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/sassValueParser/index'>;
}
declare module 'stylelint-scss/dist/utils/whitespaceChecker.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/whitespaceChecker'>;
}
