// flow-typed signature: 628513dbfa1976887fe5f324181c3784
// flow-typed version: <<STUB>>/xhr-mock_v^1.9.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xhr-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xhr-mock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xhr-mock/lib/MockRequest' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/MockResponse' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/MockXMLHttpRequest' {
  declare module.exports: any;
}

declare module 'xhr-mock/test/index' {
  declare module.exports: any;
}

declare module 'xhr-mock/test/MockRequest' {
  declare module.exports: any;
}

declare module 'xhr-mock/test/MockResponse' {
  declare module.exports: any;
}

declare module 'xhr-mock/test/MockXMLHttpRequest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xhr-mock/index' {
  declare module.exports: $Exports<'xhr-mock'>;
}
declare module 'xhr-mock/index.jsx' {
  declare module.exports: $Exports<'xhr-mock'>;
}
declare module 'xhr-mock/lib/MockRequest.js' {
  declare module.exports: $Exports<'xhr-mock/lib/MockRequest'>;
}
declare module 'xhr-mock/lib/MockResponse.js' {
  declare module.exports: $Exports<'xhr-mock/lib/MockResponse'>;
}
declare module 'xhr-mock/lib/MockXMLHttpRequest.js' {
  declare module.exports: $Exports<'xhr-mock/lib/MockXMLHttpRequest'>;
}
declare module 'xhr-mock/test/index.jsx' {
  declare module.exports: $Exports<'xhr-mock/test/index'>;
}
declare module 'xhr-mock/test/MockRequest.js' {
  declare module.exports: $Exports<'xhr-mock/test/MockRequest'>;
}
declare module 'xhr-mock/test/MockResponse.js' {
  declare module.exports: $Exports<'xhr-mock/test/MockResponse'>;
}
declare module 'xhr-mock/test/MockXMLHttpRequest.js' {
  declare module.exports: $Exports<'xhr-mock/test/MockXMLHttpRequest'>;
}
