/**
 * @module Constants/User
 * @desc User Constants
 */

import keyMirror from 'fbjs/lib/keyMirror';

/**
 * @constant {Object} SettingsConstants
 * @memberof Constants
 */
export const SettingsConstants = keyMirror({
  SETTINGS_FETCH_REQUEST: undefined,
  SETTINGS_FETCH_SUCCESS: undefined,
  SETTINGS_FETCH_FAILURE: undefined,
  SETTINGS_FETCH_CANCEL: undefined,
  SETTINGS_SOURCE_FETCH_REQUEST: undefined,
  SETTINGS_SOURCE_FETCH_SUCCESS: undefined,
  SETTINGS_SOURCE_FETCH_FAILURE: undefined,
  SETTINGS_SOURCE_FETCH_CANCEL: undefined,
  SETTINGS_SOURCE_RESET: undefined,
  SETTINGS_OPTIONS_FETCH_REQUEST: undefined,
  SETTINGS_OPTIONS_FETCH_SUCCESS: undefined,
  SETTINGS_OPTIONS_FETCH_FAILURE: undefined,
  SETTINGS_OPTIONS_FETCH_CANCEL: undefined,
  SETTINGS_ZIPCODE_FETCH_REQUEST: undefined,
  SETTINGS_ZIPCODE_FETCH_SUCCESS: undefined,
  SETTINGS_ZIPCODE_FETCH_FAILURE: undefined,
  SETTINGS_ZIPCODE_FETCH_CANCEL: undefined,
  SETTINGS_ZIPCODE_RESET: undefined,
  SETTINGS_MATRIX_FETCH_REQUEST: undefined,
  SETTINGS_MATRIX_FETCH_SUCCESS: undefined,
  SETTINGS_MATRIX_FETCH_FAILURE: undefined,
  SETTINGS_MATRIX_FETCH_CANCEL: undefined,
  SETTINGS_MATRIX_SELECT_QUANTITY: undefined,
  PRE_PRESS_TEMPLATE_FETCH_REQUEST: undefined,
  PRE_PRESS_TEMPLATE_FETCH_SUCCESS: undefined,
  PRE_PRESS_TEMPLATE_FETCH_FAILURE: undefined,
  PRE_PRESS_TEMPLATE_FETCH_CANCEL: undefined,
  PRE_PRESS_DOWNLOAD_FETCH_REQUEST: undefined,
  PRE_PRESS_DOWNLOAD_FETCH_SUCCESS: undefined,
  PRE_PRESS_DOWNLOAD_FETCH_FAILURE: undefined,
  PRE_PRESS_DOWNLOAD_FETCH_CANCEL: undefined,
  REMOVE_SELECTION_PART: undefined,
  SELECT_PREPRESS_ORIENTATION: undefined,
});
